services:
  db:
    image: mariadb:latest
    # image: mysql:lts
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: woodwiccan
      MYSQL_USER: woodwiccan
      MYSQL_PASSWORD_FILE: /run/secrets/db-user-password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-root-password
    secrets:
      - db-root-password
      - db-user-password
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-root-password
    secrets:
      - db-root-password
    ports:
      - '9991:80'
      
  woodwiccan:
    depends_on:
      - db
    build:
      context: .
    ports:
      - 9990:80
    volumes:
      - ./WC:/var/www/html/WC
      - ./sites:/var/www/html/sites
      - ./configuration:/var/www/html/configuration
      - ww-vendor:/var/www/html/vendor

    environment:
      WC_DB_SERVER: db
      WC_DB_NAME: woodwiccan
      WC_DB_USER: woodwiccan
      WC_DB_PWD_FILE: /run/secrets/db-user-password
    secrets:
      - db-root-password
      - db-user-password

volumes:
  db-data:
  ww-vendor:

secrets:
  db-user-password:
    file: ./db-user-password.txt
  db-root-password:
    file: ./db-root-password.txt
